AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal CloudFormation template to create an SNS topic and an AWS Budget with email notification

Parameters:
  BudgetAmount:
    Type: Number
    Default: 50
    Description: Monthly budget amount in USD
  AlertThresholdPercent:
    Type: Number
    Default: 80
    Description: Percentage of budget to trigger notification (e.g., 80)
  NotificationEmail:
    Type: String
    Description: Email address to receive budget alerts

Resources:
  BillingSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: financial-rag-billing-topic

  BillingSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref BillingSNSTopic
      Endpoint: !Ref NotificationEmail

  MonthlyBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetType: COST
        BudgetLimit:
          Amount: !Ref BudgetAmount
          Unit: USD
        TimeUnit: MONTHLY
        BudgetName: financial-rag-monthly-budget
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref AlertThresholdPercent
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BillingSNSTopic

Outputs:
  BudgetName:
    Description: Name of the created budget
    Value: financial-rag-monthly-budget
  SNSTopicArn:
    Description: SNS Topic ARN for billing alerts
    Value: !Ref BillingSNSTopic
