name: Workflow Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan workflows for unsupported Python versions
        run: |
          set -euo pipefail
          echo "Searching .github/workflows for disallowed python-version values..."
          bad=$(grep -R "python-version" .github/workflows || true)
          if [ -z "$bad" ]; then echo "no python-version keys found in workflows"; exit 0; fi
          echo "$bad" | grep -n "3.1" && {
            echo "Found unsupported python version '3.1' in workflows:\n"$bad
            exit 1
          } || echo "No unsupported python versions found."
